site_name: HBSM UTA Docs
nav: 
    - Home: index.md
    - Our Experiment:
        - The Detectors: The_LHC.md
    - Coding: 
        - Command Line: coding.md
        - Python/C++: python.md
        - ROOT: root.md
        - Cyberduck and Sublime: cyberduck.md
        - Github: github.md
        
    - The Computing Aspect:
        - The Tier 3: tier3.md
        - Neural Networks: neuralnets.md
    - About: about.md

theme: "material"
