site_name: HBSM UTA Docs
nav: 
    - Home: index.md
    - Our Experiment:
        - The Detectors: The_LHC.md
    - Coding: 
        - Command Line: coding.md
        - Python/C++: python.md
        - ROOT: root.md
        - Cyberduck and Sublime: cyberduck.md
        - Github: github.md
        
    - The Computing Aspect:
        - The Tier 3: tier3.md
        - The Super Computer: supercomputer.md
        - Neural Networks: neuralnets.md
        - Grid Certificates: Grid_Certificates.md 

    - Conducting Analysis:
        - Analysis: data_analysis.md
        - Writing Papers: overleaf.md
    - About: about.md

theme: "mkdocs"
# theme: "material"
